### PR TITLE
test(api): cover the mesh broker, hierarchy handlers and SSE route (43%/71%/0% → ~100% lines)

### PR DESCRIPTION
**Pull request by ZhePang**
## What

A coverage sweep across the monorepo found three API modules well below the rest of the codebase. All three carry real logic — none of them are wiring — and all three are load-bearing for the agent runtime. This PR is tests only; no source files changed.

| File | Lines before | Lines after |
| --- | --- | --- |
| `packages/api/src/mesh/server.ts` | 43.6% | **100%** |
| `packages/api/src/tools/hierarchy.ts` | 71.2% | **99.1%** |
| `packages/api/src/routes/stream.ts` | 0% | **100%** |

+1364 lines of test, 129 new/expanded cases across three files.

## How the targets were picked

Ran `@vitest/coverage-v8` per package with `--coverage.all`, excluding the DB- and key-gated suites (they abort report generation from `afterAll` without Postgres) and `src/adapters/postgres/**` (covered in CI, invisible here). The provider was installed for the sweep and is **not** committed, per `CLAUDE.md`.

Everything else came out fine: `@beevibe/core` is at 84.7% with the shortfall entirely in barrels, `test-helpers.ts`, and the live-API provider adapters. Files already claimed by open PRs (#289 `tools/mesh.ts`, #293 `routes/chat.ts` + `tools/{use-repo,watch,session-search}`, #287/#294 `web/lib` and `runtime-registry`) were deliberately left alone to avoid conflicts.

## `mesh/server.ts` — the negotiation state machine

Only the failure-propagation path had tests. The whole A↔B negotiation protocol was untested, including the two pieces most likely to break silently:

- **Round accounting.** `sendNegotiate` inserts round 1 *and* bumps `rounds_completed` in the same step — without it, B's first `respond_negotiate` re-attempts `round_number=1` and trips the UNIQUE constraint on `negotiation_round`.
- **The exchange arithmetic behind `max_rounds`.** The column counts rows, but the cap means A↔B *exchanges* — two rows each. Tests pin both sides of the boundary: 9 rows completed still lets B close exchange 5, 10 rows completed refuses to open exchange 6.

Also covered: the IC fail-fast (ICs have no `respond_negotiate`, so a negotiation against one would hang forever), the capacity gate firing before any rows are written, `counterparty_session_id` being stamped once and only from B's side, which resolver key ends up blocked after each response, the escalation sentinel releasing either side, `report_blocker`'s fire-and-forget dispatch (and that it is deliberately *not* capacity-gated), the dispatch-rejection log path, and the 5-minute resolver timeout.

## `tools/hierarchy.ts` — three untested handlers

`revise_task`, `add_to_escalation` and `create_subordinate_agent` had no handler tests at all — only the tier-gating list pinned their names.

- **`revise_task`**: each rung of the parent-only authz ladder returns its own code and none of them reach `taskService`; the revision session dispatches only when `reviseTask` actually stamped a `revision` context; `InvalidTaskTransitionError` maps to `invalid_transition` rather than the generic envelope.
- **`add_to_escalation`**: argument coercion (non-string open questions dropped, absent arrays passed as `undefined` not `[]`), the `pg_notify` refresh, `both_sides_submitted` on both branches, and that the notify does *not* fire on a failed contribution.
- **`create_subordinate_agent`**: owner/runtime inheritance, `preferred_runtime_id` inherited when present and omitted entirely when not, core-memory seeding (required blocks always, optional blocks only when supplied), the per-parent daily cap and its boundary (7 spawns still works, 8 refuses), name and `tag_line` validation including the control-character rejection, and the audit-row write failing without failing the spawn.

Plus the per-tool error envelopes and argument guards left over on the shared tools. The only lines still uncovered are the `ic_cannot_spawn` guard — `buildHierarchyTools` never hands the tool to an IC context, so it is unreachable defensive code.

## `routes/stream.ts` — no tests at all

Small file, but every line is a browser-visible contract. Driven against a real Express server on an ephemeral port with the real `SseManager`: the human-only gate registering no subscriber, the no-buffering header set, the priming `data: {}` frame (an SSE comment wouldn't fire `onmessage`, so the client health probe would never trip), per-person event filtering, the keep-alive heartbeat, and the unsubscribe that otherwise leaks a subscriber per dropped connection.

Uses `node:http` rather than `fetch` because undici holds an aborted connection open for ~4s, which made the disconnect assertion slow — the file runs in 119ms instead of 4.1s as a result.

## Verification

- `npx tsc -p packages/api/tsconfig.json --noEmit` — clean
- `npx eslint` on the three files — clean
- Full API suite: **920 tests pass**. The 9 failing files are the DB-gated integration suites failing on `DATABASE_URL_TEST env var is required` — the pre-existing environmental baseline documented in `CLAUDE.md`, unchanged by this PR.
- **Every new assertion was mutation-checked** against the source it covers. Flipping `>=` to `>` on the daily cap, dropping the control-character check, defeating the `not_parent` authz branch, widening the `tag_line` limit, replacing the exchange division, removing the `unsubscribe()` call, swapping the priming frame for a comment, dropping `X-Accel-Buffering`, and stretching the heartbeat interval each fail exactly the tests that claim to cover them.

---
_Generated by [Claude Code](https://claude.ai/code/session_016GXkpfxSchB2dxCKBxdCqH)_

### CODE REVIEW

**Comment by ZhePang** [comment]
CI status: **Sign-off check ✅** (I'd missed the DCO trailer on the first push; amended and force-pushed). **Unit + Integration Tests ❌ — but the failure is pre-existing on `main`, not from this PR.**

All 6 failures are in a single file this PR does not touch, `packages/core/src/adapters/postgres/room-repo.test.ts`:

```
× rooms.listMemberPersonIds is not a function        (×2)
× rooms.areAgentsCoMembers is not a function         (×3)
× breaks a created_at tie by id so the order is stable
    AssertionError: expected [ 'rmsg_k4l6…' ] to deeply equal [ 'rmsg_Tzk3…' ]

Test Files  1 failed | 58 passed | 1 skipped (60)
```

Those two repo methods were removed by #285; the test file still calls them. The tie-break failure is a collation issue in the same file. This is exactly the scope of open PR #291 — *"unbreak main — drop tests of methods removed by #285, pin the tie-break test's collation"* — so the fix belongs there rather than here, and duplicating it in this branch would just conflict.

This PR's diff against its base (`0323ad0`) is three test files and nothing else:

```
packages/api/src/mesh/server.test.ts
packages/api/src/routes/stream.test.ts
packages/api/src/tools/hierarchy.test.ts
```

None of the three appear anywhere in the failure output, and the other 58 test files pass — including all of the new cases here.

Once #291 lands I'll merge `main` into this branch so CI re-runs against a green base. Happy to rebase sooner if you'd rather see this one green independently.

---
_Generated by [Claude Code](https://claude.ai/code)_
